version: '3'

services:
  backend:
    build: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 5000
    user: 1000:1000